// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "a04e3c7e-edeb-4345-8149-0064292553ed");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1672920116);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1672920088);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1672920087);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1672920145);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{22b4dbd7-8477-4d71-9d9e-5c5f066d1645}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1672920085);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 133);
user_pref("browser.newtabpage.activity-stream.impressionId", "{6a80ad0b-eb89-4e14-acb9-dd22a1f93a55}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1672920087);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1672920114842");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1672921895842");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1672920092135");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1672941692135");
user_pref("browser.search.region", "PK");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20221216042651");
user_pref("browser.startup.homepage_override.mstone", "108.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1672920086);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\"],\"currentVersion\":18,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1672920086831");
user_pref("distribution.canonical-002.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "108.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "PK");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "30511bb81e7648099e883e23a48be030");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.installedDistroAddon.langpack-en-US@firefox.mozilla.org", true);
user_pref("extensions.lastAppBuildId", "20221216042651");
user_pref("extensions.lastAppVersion", "108.0.1");
user_pref("extensions.lastPlatformVersion", "108.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"1d2394b1-db9d-4def-a495-89e605b9331a\",\"pictureinpicture@mozilla.org\":\"37ee0091-186a-49cb-8dd8-b0240a8d16e4\",\"screenshots@mozilla.org\":\"db6e34c9-863b-4399-972f-3fddb529467e\",\"webcompat-reporter@mozilla.org\":\"433208f9-e867-492a-aca7-25be922aef77\",\"webcompat@mozilla.org\":\"93b918d6-98aa-4881-845c-de39f1ebb1b6\",\"default-theme@mozilla.org\":\"97779c03-196b-4fa7-807c-48e212722296\",\"addons-search-detection@mozilla.com\":\"bd32c6e2-3406-44ae-866e-306842ba2630\",\"google@search.mozilla.org\":\"60cb7aee-5052-4a42-b7e0-74a217df670c\",\"amazondotcom@search.mozilla.org\":\"8afcc308-b09d-4e01-ade2-0def5eee73fb\",\"wikipedia@search.mozilla.org\":\"dc78f41e-273f-4c40-9f3e-3f210a831141\",\"bing@search.mozilla.org\":\"92f5c0ba-69d5-4678-b465-147d9461251b\",\"ddg@search.mozilla.org\":\"ba04a6a7-a1be-4b61-80fa-66af378663a8\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1672920086);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "3bc61313-1115-47cb-90b0-fd8ae32b78a4");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("toolkit.startup.last_success", 1672920084);
user_pref("toolkit.telemetry.cachedClientID", "cc307a00-a56f-4e01-9821-85659451a7e3");
user_pref("toolkit.telemetry.previousBuildID", "20221216042651");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
